"""create_candidate_and_sequence_run_tables

Revision ID: 5e057cad4e8b
Revises: bccd4db21d6a
Create Date: 2026-03-28 15:29:02.881323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e057cad4e8b'
down_revision: Union[str, None] = 'bccd4db21d6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_email'), 'candidate', ['email'], unique=True)
    op.create_table('sequence_run',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', name='sequencerunstatus'), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_id'], ['sequence.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sequence_run_candidate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('sequence_run_id', sa.Integer(), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'REPLIED', 'UNSUBSCRIBED', name='sequenceruncandidatestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sequence_run_id'], ['sequence_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'sequence_run_id', name='uq_sequence_run_candidate')
    )
    op.create_table('sequence_run_candidate_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sequence_run_candidate_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('ENROLLED', 'EMAIL_SCHEDULED', 'EMAIL_SENT', 'EMAIL_FAILED', 'REPLY_RECEIVED', 'REPLY_CLASSIFIED', 'REPLY_SENT', 'COMPLETED', 'UNSUBSCRIBED', name='eventtype'), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=True),
    sa.Column('external_message_id', sa.String(), nullable=True),
    sa.Column('external_schedule_id', sa.String(), nullable=True),
    sa.Column('external_provider', postgresql.ENUM('NYLAS', name='integrationprovider', create_type=False), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sequence_run_candidate_id'], ['sequence_run_candidate.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sequence_run_candidate_event_external_message_id'), 'sequence_run_candidate_event', ['external_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sequence_run_candidate_event_external_message_id'), table_name='sequence_run_candidate_event')
    op.drop_table('sequence_run_candidate_event')
    op.drop_table('sequence_run_candidate')
    op.drop_table('sequence_run')
    op.drop_index(op.f('ix_candidate_email'), table_name='candidate')
    op.drop_table('candidate')

    op.execute("DROP TYPE IF EXISTS eventtype")
    op.execute("DROP TYPE IF EXISTS sequenceruncandidatestatus")
    op.execute("DROP TYPE IF EXISTS sequencerunstatus")
    # ### end Alembic commands ###
